version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mathjs
    versions:
    - 9.1.0
    - 9.2.0
    - 9.3.0
    - 9.3.1
  - dependency-name: sequelize
    versions:
    - 6.5.0
    - 6.5.1
    - 6.6.1
  - dependency-name: ejs
    versions:
    - 3.1.5
